<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>FastCraft3D</RootNamespace>
    <AssemblyName>3DFastCraft</AssemblyName>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
    <Version>1.7.3</Version>
    <Product>3DFastCraft</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.SharpDX.Core.Wpf" Version="2.27.3" />
  </ItemGroup>

</Project>
